version: 0.0
os: linux
files:
  - source: /
    destination: /srv/app

hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: root
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 300
      runas: root
