module.exports = {
  projects: [
    '<rootDir>/apps/client',
    '<rootDir>/apps/server',
    '<rootDir>/libs/ui',
    '<rootDir>/apps/client',
    '<rootDir>/apps/extensions',
    '<rootDir>/libs/client/feature-home',
    '<rootDir>/libs/client/shared/data-access-auth',
    '<rootDir>/libs/client/shared/feature-apollo',
    '<rootDir>/libs/client/shared/feature-auth',
    '<rootDir>/libs/client/shared/util-common',
    '<rootDir>/libs/client/shared/util-auth',
    '<rootDir>/libs/client/shared/data-access-apollo',
    '<rootDir>/libs/home/feature-comming-soon',
    '<rootDir>/libs/me/data-access-me',
    '<rootDir>/libs/bookmark/data-access-bookmark',
    '<rootDir>/libs/bookmark/feature-bookmark',
    '<rootDir>/libs/shared/data-access-user',
    '<rootDir>/libs/login/feature-login',
    '<rootDir>/libs/login/data-access-login',
    '<rootDir>/libs/bookmark/feature-feed',
    '<rootDir>/libs/shared/data-access-pagination-bookmarks',
  ],
};
