// MEMO(Teddy): https://www.marvel.com/characters
export const OPERATION_TEST_USERS = [
  //   {
  //     name: '',
  //     email: '',
  //     avatarUrl: '',
  //     timezone: '',
  //   },
  {
    name: 'Black Widow',
    email: 'BlackWidow@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/433ybv_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Red Guardian',
    email: 'RedGuardian@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/435rgd_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'TaskMaster',
    email: 'TaskMaster@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/173tsk_com_crd_02.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Shang-chi',
    email: 'Shang-chi@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/242shc_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Spider-man',
    email: 'Spider-man@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/037smm_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Knull',
    email: 'Knull@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/03-knull_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Ajak',
    email: 'Ajak@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/445ajk_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Aladi ko eke',
    email: 'AladiKoEke@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/aladi_ko_eke.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Albert',
    email: 'Albert@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/albertandelsie.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Brawn',
    email: 'Brawn@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/046hac_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Amphibion',
    email: 'Amphibion@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/amphibion_1.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Android man',
    email: 'AndroidMan@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/anman.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Anole',
    email: 'Anole@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/anole1.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Anti-cap',
    email: 'Anti-cap@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/anticap_head.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Anvil',
    email: 'Anvil@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/acotilletta2--anvil_(ja).jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Arcade',
    email: 'Arcade@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/ohitsme--arcade.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Arch-e-5912',
    email: 'Arch-e-5912@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/arch-e-5912.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Arishem',
    email: 'Arishem@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/arishem-the-judge-earth-616.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Armageddon',
    email: 'Armageddon@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/armageddon.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Asbestos man',
    email: 'AsbestosMan@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/asbestos_man.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Asp',
    email: 'Asp@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/asp-zircher.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Asmodeus',
    email: 'Asmodeus@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/asmodeus_(lord)_head.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Atlas',
    email: 'Atlas@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/atlas442x350.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Authority',
    email: 'Authority@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/authority442.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Axon',
    email: 'Axon@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/axon.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Bakuto',
    email: 'Bakuto@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/153bak_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Baron Mordo',
    email: 'BaronMordo@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/469mdo_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Barbarus',
    email: 'Barbarus@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/bbs.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Basher',
    email: 'Basher@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/basher.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Ben Parker',
    email: 'BenParker@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/benparker-6078.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Ben Urich',
    email: 'BenUrich@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/ben_urich.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Bengal',
    email: 'Bengal@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/ohitsme--bengal_(duc_no_tranh).jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Big Zero',
    email: 'BigZero@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/acotilletta2--big_zero_new.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Black Jack Tarr',
    email: 'BlackJackTarr@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/jack-tarr-earth-616_1.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Black Mamba',
    email: 'BlackMamba@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/blackmamba442.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Black Tom',
    email: 'BlackTom@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/blacktomcassidy.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Blade',
    email: 'Blade@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/130bld_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Blistik',
    email: 'Blistik@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/blistik_head.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Blood Spider',
    email: 'BloodSpider@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/bloodspider_head.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Blue Shield',
    email: 'BlueShield@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/blueshield1.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Boom',
    email: 'Boom@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/ohitsme--boom_hd.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Boom-boom',
    email: 'Boom-boom@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/new_mutants_2019_6_boom_boom_0.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Box',
    email: 'Box@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/box_roger442.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Bucky',
    email: 'Bucky@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/buckyhusk_head.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Bullseye',
    email: 'Bullseye@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/198bsy_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Cable',
    email: 'Cable@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/056cbl_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Caliban',
    email: 'Caliban@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/151cbn_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Captain America',
    email: 'CaptainAmerica@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/cptamericahsofm.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Captain Universe',
    email: 'CaptainUniverse@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/cap-daredevil.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Carina Walters',
    email: 'CarinaWalters@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/ohitsme--carina.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Cerebra',
    email: 'Cerebra@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/cbra2099.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Collective Man',
    email: 'CollectiveMan@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/collective_man.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Colossus',
    email: 'Colossus@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/235cls_com_crd_01.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Controller',
    email: 'Controller@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/cont.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Crossfire',
    email: 'Crossfire@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/crossfire_head.jpg',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Cyclone',
    email: 'Cyclone@gmail.com',
    avatarUrl: 'https://terrigen-cdn-dev.marvel.com/content/prod/1x/cyclonehusk_head.jpg',
    timezone: 'Asia/Seoul',
  },
];
